name: Release on tag

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set VERSION from tag
        id: vars
        run: |
          VERSION="${GITHUB_REF_NAME}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Generate release notes (git-cliff)
        uses: orhun/git-cliff-action@v4
        with:
          config: ./cliff.toml
          args: --tag "${{ steps.vars.outputs.version }}" --latest --strip header
        env:
          OUTPUT: CHANGELOG-RELEASE.md

      - name: Show generated notes (debug)
        run: |
          echo "----- BEGIN NOTES -----"
          cat CHANGELOG-RELEASE.md
          echo "----- END NOTES -----"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          name: brave-sync ${{ steps.vars.outputs.version }}
          body_path: CHANGELOG-RELEASE.md
          draft: false
          prerelease: ${{ contains(steps.vars.outputs.version, '-') }} # v1.2.3-rc.1 => prerelease

